import Link from 'next/link'
import React from 'react'

export const metadata = {
  title: 'Throwback | Mens',
  description: 'Generated by create next app',
}

const page = () => {
  return (
    <div>
      <section className="flex flex-col px-2 py-16 items-center">
        <h2 className="font-bold px-4 my-8 tracking-widest text-base">
          MENS FASHION
        </h2>
        <div className="flex flex-col items-center justify-center">
          <div className="flex flex-col mx-2 my-2">
            <Link href={'/product'}>
              <img
                className="w-80 object-cover lg:w-60 lg:h-60"
                src="/loro2.jpg"
                alt=""
              />
            </Link>
            <h3 className="text-base font-semibold mt-1">Blue Trouser - H&M</h3>
            <p className="text-sm font-medium">₹799</p>
          </div>
          <div className="flex flex-col mx-2 my-2">
            <Link href={'/product'}>
              <img
                className="w-80 object-cover lg:w-60 lg:h-60"
                src="/loro3.jpg"
                alt=""
              />
            </Link>
            <h3 className="text-base font-semibold mt-1">White Trouser - H&M</h3>
            <p className="text-sm font-medium">₹1199</p>
          </div>
        </div>
        <h2 className="w-full text-center my-8 font-semibold px-4 text-sm">SHOW MORE</h2>
      </section>
    </div>
  )
}

export default page