import Link from 'next/link'
import React from 'react'

export const metadata = {
  title: 'Throwback | Shirts',
  description: 'Generated by create next app',
}

const page = () => {
  return (
    <div>
      <section className="flex flex-col px-2">
        <h2 className="font-bold px-4 my-8 tracking-widest text-base">
          NEW ARRIVALS
        </h2>
        <div className="flex items-center justify-center flex-wrap">
          <div className="flex flex-col mx-2">
            <Link href={'/product'}>
              <img
                className="object-cover w-36"
                src="/Shirt (1).jpg"
                alt=""
              />
            </Link>
            <h3 className="text-sm font-semibold">Blue Trouser</h3>
            <p className="text-xs">₹799</p>
          </div>
          <div className="flex flex-col mx-2">
            <Link href={'/product'}>
              <img
                className="object-cover w-36"
                src="/Shirt (2).jpg"
                alt=""
              />
            </Link>
            <h3 className="text-sm font-semibold">Blue Trouser</h3>
            <p className="text-xs">₹799</p>
          </div>
        </div>
        <h2 className="w-full text-center my-8 font-semibold px-4 text-sm">SHOW MORE</h2>
      </section>
    </div>
  )
}

export default page